server:
  port: 8082

client:
  customer:
    url: http://localhost:8081/api/v1/customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  application:
    name: account-service
  web-flux:
    base-path: '/api/v1'
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_account
