server:
  port: 8082

client:
  customer:
    url: http://localhost:8081/customer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_account
