server:
  port: 8081

spring:
  application:
    name: customer-service
  web-flux:
    base-path: '/api/v1'
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_customer
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8099/eureka/
